

group 'com.deepar.ai'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        flatDir {
            dirs 'libs'
        }
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.deepar.ai'
    compileSdkVersion 36

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
       /* sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8*/
    }

    defaultConfig {
        minSdkVersion 23
    }
}

dependencies {
    api (name: 'deepar', ext: 'aar')
    implementation 'androidx.camera:camera-lifecycle:1.5.1'
    implementation "androidx.camera:camera-camera2:1.5.1"
}
